application:
   allowedOrigins:
      - http://localhost:3000/
      - https://showcase-frontend-eta.vercel.app/
   frontendBaseUrl: ${SHOWCASE_FRONTEND_BASE_URL}
   tokenSecret: ${SHOWCASE_BACKEND_TOKEN_SECRET}
   
spring:
   data:
      mongodb:
         uri: ${SPRING_DATA_MONGODB_URI}
         database: showcase
   security:
      oauth2:
         client:
            registration:
               google:
                  clientId: ${SHOWCASE_BACKEND_GOOGLE_CLIENT_ID}
                  clientSecret: ${SHOWCASE_BACKEND_GOOGLE_CLIENT_SECRET}
                  scope:
                     - profile
                     - email
               
springdoc:
   default-consumes-media-type: application/json
   default-produces-media-type: application/json
   override-with-generic-response: false
   swagger-ui:
      operations-sorter: alpha
      path: /docs
      supportedSubmitMethods: []
      tagsSorter: alpha
                     
                                
